version: "3.4"
services:
    nopcommerce_web:
        image: "elestio4test/nopcommerce:latest"
        container_name: nopcommerce
        ports:
            - "80:80"
        depends_on:
            - nopcommerce_database
        networks:
            - grid

    nopcommerce_database:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: nopcommerce_mssql_server
        environment:
            SA_PASSWORD: "password123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        networks:
            - grid

    selenium-hub:
        image: selenium/hub
        ports:
            - "4442-4444:4442-4444"
        networks:
            - grid

    node-chrome:
        image: selenium/node-chrome
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        networks:
            - grid

    node-edge:
        image: selenium/node-edge
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        networks:
            - grid


networks:
    grid:
        driver: bridge



